### ISSUE TITLE
Crash: Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tdc22** [AlbinoGeek/sc2-rsu#16]
I just leave the program (`sc2-rsu-0.4.1-linux-amd64`) open for a while after I played some matches and at some point I get this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98f6e3]

goroutine 11 [running, locked to thread]:
fyne.io/fyne/widget.(*tableRenderer).moveIndicators(0xc000228a10)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/widget/table.go:317 +0x183
fyne.io/fyne/widget.(*tableRenderer).Layout(0xc000228a10, 0x283, 0x1d1)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/widget/table.go:242 +0x2f
fyne.io/fyne/internal/driver/glfw.updateLayout(0xecff00, 0xc0001320c0)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/canvas.go:633 +0x11e
fyne.io/fyne/internal/driver/glfw.(*glCanvas).ensureMinSize.func1(0xc0018b8370)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/canvas.go:335 +0x168
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree.func2(0xecf480, 0xc001a07900, 0xecfea0, 0xc000040a80)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/canvas.go:513 +0xd8
fyne.io/fyne/internal/driver.walkObjectTree(0xecf480, 0xc001a07900, 0xecfea0, 0xc000040a80, 0x198, 0x5f, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/util.go:88 +0x27f
fyne.io/fyne/internal/driver.walkObjectTree(0xecfea0, 0xc000040a80, 0xecff00, 0xc0001320c0, 0xa6, 0x5b, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/util.go:81 +0x1f6
fyne.io/fyne/internal/driver.walkObjectTree(0xecff00, 0xc0001320c0, 0xecf1e0, 0xc0000a7270, 0xa6, 0x40, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/util.go:81 +0x1f6
fyne.io/fyne/internal/driver.walkObjectTree(0xecf1e0, 0xc0000a7270, 0xecf1e0, 0xc0000a67d0, 0xa2, 0x3c, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/util.go:81 +0x1f6
fyne.io/fyne/internal/driver.walkObjectTree(0xecf1e0, 0xc0000a67d0, 0xecf1e0, 0xc0000a6820, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/util.go:81 +0x1f6
fyne.io/fyne/internal/driver.walkObjectTree(0xecf1e0, 0xc0000a6820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x7fffffff, ...)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/util.go:81 +0x1f6
fyne.io/fyne/internal/driver.WalkVisibleObjectTree(0xecf1e0, 0xc0000a6820, 0xc0020b5ce8, 0xc0020b5cc0, 0x46371f)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/util.go:25 +0x82
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTree(0xc0000ca500, 0xc0012ac5c0, 0x0, 0xc0020b5db8)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/canvas.go:519 +0x15c
fyne.io/fyne/internal/driver/glfw.(*glCanvas).walkTrees(0xc0000ca500, 0x0, 0xc0020b5db8)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/canvas.go:526 +0x4f
fyne.io/fyne/internal/driver/glfw.(*glCanvas).ensureMinSize(0xc0000ca500, 0xc0020b5e28)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/canvas.go:340 +0x98
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/loop.go:156 +0x40
fyne.io/fyne/internal/driver/glfw.(*window).RunWithContext(0xc000230000, 0xc0020b5e60)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/window.go:1095 +0x38
fyne.io/fyne/internal/driver/glfw.(*gLDriver).repaintWindow(0xc0000a6fa0, 0xc000230000)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/loop.go:155 +0x60
fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc0000a6fa0, 0xc000038780, 0xc0000a7040)
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/loop.go:208 +0x223
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread
	/go/pkg/mod/fyne.io/fyne@v1.4.2/internal/driver/glfw/loop.go:182 +0xbd
```

**Comment by AlbinoGeek** [comment]
Thank you for trying out my software and filing an issue report!

I will investigate this on the weekend, hoping to actively develop this software going forward.
